# Generated by Django 4.0.4 on 2022-05-19 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aktivitas',
            fields=[
                ('aktivitas_id', models.AutoField(primary_key=True, serialize=False)),
                ('kode_jadwal', models.CharField(max_length=500)),
                ('status', models.CharField(max_length=500)),
                ('amalan', models.IntegerField()),
                ('user', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Amalan',
            fields=[
                ('amalan_id', models.AutoField(primary_key=True, serialize=False)),
                ('nama_amalan', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=500)),
                ('username', models.CharField(max_length=500)),
                ('password', models.CharField(max_length=500)),
            ],
        ),
    ]
