# Generated by Django 4.0.4 on 2022-05-20 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KareemApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Amalan',
        ),
        migrations.AlterField(
            model_name='aktivitas',
            name='amalan',
            field=models.CharField(max_length=500),
        ),
    ]
